name: build exe
on:
  release:
    types: [published]
  schedule:
    - cron: '21 0 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Test Build Python Exe
        uses: eric2788/pyinstaller-build@master
        with:
          main: main
          artifact: Program
          use-dependencies: true
          python_version: 3.12.2
          pyinstaller_version: 5.12
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: python_exe
          path: dist
