name: build exe
on:
  release:
    types: [published]
  schedule:
    - cron: '21 0 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9.18'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'python_exe'
          options: --onefile, --name "python_main_py", --windowed,
