name: build exe
on:
  release:
    types: [published]
  schedule:
    - cron: '21 0 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Run checkin
        run: |
          python3 ./main.py
